### PR TITLE
Added Typescript Typings

### PR DESCRIPTION
**Pull request by PaitoAnderson**
Not sure if you are interested in supporting Typescript users, but I did this while using your library for myself and thought I would share. Thanks!

### CODE REVIEW

**Comment by prabhu** [comment]
Of course. The whole world is like TypeScript now mate!

**Comment by coreh** [comment]
Any updates on this? Would be nice to get this merged in

**Comment by PaitoAnderson** [comment]
If the answer is no, I'll gladly submit a PR to [DefinitelyTyped](/DefinitelyTyped/DefinitelyTyped) to get typings added there.

**Comment by henrikra** [comment]
@PaitoAnderson Can you make PR to DefinitelyTyped?

**Comment by DavidNorena** [comment]
@PaitoAnderson  any luck friend ?

**Comment by slavikdenis** [comment]
This would be much appreciated

**Comment by slavikdenis** [comment]
Any updates on this one? Thanks :)

**Comment by slavikdenis** [comment]
bump?

**Comment by slavikdenis** [comment]
bump

**Comment by ken0x0a** [comment]
no stale

**Pull request closed without merging**
