### PR TITLE
Fix: When app's in background, Android cannot trigger registerNotificationOpened when user press on banner 

### PR DESCRIPTION
**Pull request by ttkien**
I think this PR #358 made the Android cannot trigger registerNotificationOpened when user press on banner. For more details, you can read the issue here #498

The reason is If users press on banner when app is in background. The notification doesn't have extra bundle pushNotification

### CODE REVIEW

**Comment by gavinlight** [comment]
This fixed background notifications on android for me. Can this be merged?

**Comment by taduyde** [comment]
The same issue for lasted version, Please merge it ASAP

**Comment by aniravi24** [comment]
This fixes it for me as well!

**Comment by hienpham2102** [comment]
This fixed in background for  me. tks

**Comment by SaeedZhiany** [comment]
@yogevbd 

is this PR included in a new publish? or it's not published on npm yet?

**Comment by ciprian-iacob** [comment]
@yogevbd Are there any plans to release a new version with this fix please? Thanks.

**Comment by yogevbd** [comment]
@ciprian-iacob 3.3.0 is now released 🎉

**Comment by ciprian-iacob** [comment]
@yogevbd Thank you! Great effort we all appreciate it.

**Pull request merged**
