### PR TITLE
Compatibility to Min SDK16

### PR DESCRIPTION
**Pull request by ulfgebhardt**
This PR reduces the required minSDK from 19 to 16 and includes ~1250 more supported android devices.

The `NotificationCompat.Builder` class is used instead of `Notification.Builder` for building Notifications on all Android Versions. This might require changes of the coresponding types in the custom code applied in your application (just change the type) - this is exactly then the case when you reference `getNotificationBuilder` from this library. (Example see [here](https://github.com/demokratie-live/democracy-client/commit/de4cd0b0012fae75957169321aa8df313099544b))

This fixes https://github.com/wix/react-native-notifications/issues/263

See more:
- https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder
- https://stackoverflow.com/questions/28001194/java-lang-nosuchmethoderror-android-app-notificationbuilder-setcolor

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
Tested on Android 4.1, 6.0 - working fine

Pinging all Developers, Issue Participants and Reviewers in oder to get more Test Results - to get this merged

Developers:
- @diegolmello 

Issue Participants:
- @xralphack
- @st167566
- @cassianomon
- @RyanThomas73
- @jsamr

Reviewers:
- @andrei-m-code
- @ButtersHub

Please post your positive or negative test results here in oder to get this merged or changed

**Comment by slavikdenis** [comment]
Any updates on this one? Thanks :)

**Comment by ulfgebhardt** [comment]
@slavikdenis its working for us for ~4months without problems
Just waiting for the maintainers @andrei-m-code @ButtersHub to approve

**Comment by slavikdenis** [comment]
Sorry, by updates I meant updates on merging and releasing this :)

**Comment by ulfgebhardt** [comment]
bump

**Comment by evdhoudt** [comment]
Will the min sdk version be reverted any time soon?

**Comment by johndturn** [comment]
@ulfgebhardt I think that this PR will also fix an issue that I'm running into (as seen in the issue that I referenced above). I wonder if fixing the merge conflicts would help to get this merged in?

**Comment by ulfgebhardt** [comment]
@johndturn It certainly did not help before ;-). We are currently in the process to remove this library from our App. If we happen to keep it in for some reason, I will provide fixed for this PR.

But feel Free just to fork from this PR, fix the conflicts and PR it yourself <3

**Comment by johndturn** [comment]
@ulfgebhardt haha... Good point. Sounds good, will do. I just didn't want to step on your toes if you were going to. 

@yogevbd As you mentioned V3 in #373, is this issue already solved there, or would this be beneficial for it?

**Comment by yogevbd** [comment]
@johndturn it's solved in V3. 😊

**Comment by sm2017** [comment]
@yogevbd I have this problem in latest version, Why the PR is closed! why it no merged?

**Comment by guyca** [comment]
Hey guys, sorry for the delay in handling this PR.

We've discussed this matter internally and have decided against supporting older OS versions. While the changes proposed in this PR are minimal, we're not developing nor testing against these old versions and as a result decided we can't support them.

**Pull request closed without merging**
