### PR TITLE
Change the way the initial notification is extracted from intent at

### PR DESCRIPTION
**Pull request by kristofb**
application startup.

Tested on different Android versions up to 13

### CODE REVIEW

**Comment by the-skins-app** [comment]
Well done! This works for me on SDK 33. Without it, `Notifications.getInitialNotification` absolutely does not work.

Please merge.

**Comment by greenimpala** [comment]
For me this works on the *very first* notification when the app in installed. Once the app is open and force quite, subsequent notifications end up `undefined` again.

**Review by numandev1 — APPROVED** [review]
working good

**Comment by kristofb** [comment]
I just rebased my branch on master. No more changes, for me, this hotfix is working well based on master (release 4.3.5)

**Comment by DanielEliraz** [comment]
@kristofb what about the case @greenimpala [wrote](https://github.com/wix/react-native-notifications/pull/966#issuecomment-1592685182)

**Comment by DanielEliraz** [comment]
hey, this change was added in #983 and released in 5.0.0. please verify it

**Pull request closed without merging**
