### PR TITLE
Fix: Android crash when opening notifications

### PR DESCRIPTION
**Pull request by C-Flatla**
# What's in this PR?
This PR fixes a `NullPointerException` on Android when app is resumed by opening a notification.

### Why was this PR created?
This fixes issues:
- #951 
- #910

### Quick summary of the changes you made
- Wrapped all calls of `mNotificationProps.asBundle()` in `try/catch` to prevent app crashes

### Any necessary explanation of decisions you made
- We originally implemented the solution in issue #951, but still saw crashes so expanded the fix
- We weren't able to reliably reproduce the crash, but crashes have stopped 😅 

# Picture of cat
cat

### CODE REVIEW

**Comment by fotos** [comment]
Shouldn't we be working on fixing the underlying (root) cause instead of sweeping the problem under the (logging) rug? 🤔

Despite the various problems this library has and the numerous hours I spent debugging (and still do) to get Android to handle notifications correctly in all states (dead/background/foreground), personally, I'm not very fond of the approach taken here.

**Review by DanielEliraz — APPROVED** [review]
Thanks a lot!

**Comment by DanielEliraz** [comment]
> Shouldn't we be working on fixing the underlying (root) cause instead of sweeping the problem under the (logging) rug? 🤔
> 
> Despite the various problems this library has and the numerous hours I spent debugging (and still do) to get Android to handle notifications correctly in all states (dead/background/foreground), personally, I'm not very fond of the approach taken here.

Of course, you're right but a crash is unacceptable

**Comment by C-Flatla** [comment]
@DanielEliraz is there anything I need to do to get this merged in? I merged in latest `master` so it was up to date 😄.

**Comment by DanielEliraz** [comment]
@C-Flatla  Will be soon in production

**Pull request merged**
