### PR TITLE
Fix android build for RN 0.72

### LINKED ISSUE #975: Error after upgrading to React Native 0.72
After upgrading to React Native 0.72 and trying to start the App, I get this error now:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/repo-template/node_modules/react-native-notifications/lib/android/app/build.gradle' line: 100
> 
> * What went wrong:
> Execution failed for task ':tasks'.
> > Could not create task ':react-native-notifications:testReactNative60DebugUnitTest'.
>    > No signature of method: org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.enabled() is applicable for argument types: (Boolean) values: [true]

### PR DESCRIPTION
**Pull request by jshiherlis**
Fix #975 
https://github.com/wix/react-native-notifications/issues/975

Replace deprecated method setEnabled by required.set()
Use [getRequired()](https://docs.gradle.org/7.3/javadoc/org/gradle/api/reporting/Report.html#getRequired--).set() instead.

### CODE REVIEW

**Review by kacgrzes — APPROVED** [review]
Looking good for me

**Review by my-name-is-nheo — APPROVED** [review]

**Comment by arashkevich25** [comment]
@DanielEliraz can we merge it ?

**Comment by mdidehbanmehr** [comment]
Let's merge this please

**Review by DanielEliraz — APPROVED** [review]
Thanks

**Pull request merged**
