### PR TITLE
Migrated from GCM to FCM as per Google's recommendation

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Basically just followed:

https://developers.google.com/cloud-messaging/android/android-migrate-fcm

### CODE REVIEW

**Comment by cem2ran** [comment]
@Benjamin-Dobell Any plans on adding iOS support?

**Comment by Benjamin-Dobell** [comment]
@cem2ran #62 is needed to implement FCM on iOS. However, that pull request doesn't actually link in FCM or set it up, it just makes it possible to do so.

Just follow the official Firebase iOS integration steps:

https://firebase.google.com/docs/cloud-messaging/ios/client

However, make sure you disable message swizzling (explained near the top of guide). Your `AppDelegate.m` will end up looking something like:

```
@import FirebaseCore;
@import FirebaseInstanceID;
@import FirebaseMessaging;

// Other headers

...

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
	[FIRApp configure];

	// ...
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
	[RNNotifications didRegisterUserNotificationSettings:notificationSettings];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeSandbox];
	[RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:[[FIRInstanceID instanceID] token]];

  [self connectToFcm];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
	[RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
{
  [[FIRMessaging messaging] appDidReceiveMessage:notification];
	[RNNotifications didReceiveRemoteNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
	[RNNotifications didReceiveLocalNotification:notification];
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{
  [[FIRMessaging messaging] disconnect];
}

- (void)applicationWillEnterForeground:(UIApplication *)application
{
  [self connectToFcm];
}

- (void)connectToFcm
{
  if ([[FIRInstanceID instanceID] token])
  {
    [[FIRMessaging messaging] disconnect];
    [[FIRMessaging messaging] connectWithCompletion:^(NSError * _Nullable error) {
      if (error)
      {
        NSLog(@"Unable to connect to FCM. %@", error);
      }
      else
      {
        NSLog(@"Connected to FCM.");
      }
    }];
  }
}

@end
```

Note that we're passing the FCM token to `RNNotifications`, it is _not_ the same as the APN device token, hence #62.

**Comment by Benjamin-Dobell** [comment]
Refactored (much less code in general) and fixed some bugs. In particular, we now properly handle a race condition between Firebase and React Native context initialisation; if Firebase gets back to use when the React Context _does_ exist, but isn't fully initialised (this situation was never handled in the past).

**Comment by Benjamin-Dobell** [comment]
New drastically refactored pull request will come shortly.

**Comment by Benjamin-Dobell** [comment]
As promised, refactored and extended pull request: https://github.com/wix/react-native-notifications/pull/71

**Comment by Winglonelion** [comment]
I just take a local test your pr. It work well! And gcm deprecated from April 10 2018, please merge this.

**Pull request closed without merging**
