### PR TITLE
Fix foreground notification icon color issue

### PR DESCRIPTION
**Pull request by patrickyin**
This PR is for fix issue: #494

### CODE REVIEW

**Comment by simonasdev** [comment]
works indeed. Thanks!

**Comment by anisimov74** [comment]
@patrickyin could you please add a documentation?

**Comment by patrickyin** [comment]
No problem. will do @anisimov74

**Comment by bossajie** [comment]
Do the color of the icon on notification also supported Android 5.0 / Lollipop and below? @patrickyin  @anisimov74

**Comment by bossajie** [comment]
image
Is there any change that I can put colors on the icon above there?
I am using Android 10 version on my actual device.

**Pull request merged**
