### PR TITLE
Fix: registerNotificationOpened not triggered on Android

### PR DESCRIPTION
**Pull request by ttkien**
I think this PR https://github.com/wix/react-native-notifications/pull/358 made the Android cannot trigger registerNotificationOpened when user press on banner. For more details, you can read the issue here https://github.com/wix/react-native-notifications/issues/498

The reason is If users press on banner when app is in background. The notification doesn't have extra bundle `pushNotification`

### CODE REVIEW

**Comment by dziraf** [comment]
Yes, this fixed the problem for me.

**Comment by vomchik** [comment]
Please merge it asap.

**Comment by ttkien** [comment]
@yogevbd Could you review these changes?

**Comment by gavinlight** [comment]
Can this be merged?

**Comment by rnnyrk** [comment]
Would be really nice if this can be reviewed and merged :)

**Comment by gavinlight** [comment]
Again, can this be reviewed and merged? I'm waiting for this change

**Comment by SaeedZhiany** [comment]
@yogevbd please review and merge this.

**Comment by bobbyrinaldy** [comment]
nothing action on this one ? i needed ASAP

**Comment by williamcardozo** [comment]
any update on this @yogevbd ?

**Comment by bossajie** [comment]
btw, how can I get this changes?

**Comment by anisimov74** [comment]
@yogevbd i can confirm that this PR works for me.

**Comment by bossajie** [comment]
How can I apply this PR on my react native project?

**Comment by anisimov74** [comment]
@bossajie you should clone the project, apply changes yourself or merge the PR into your clone project and use `git://github.com/YOURGITHUBNAME/react-native-notifications.git#COMMIT_HASH`. 
See also https://github.com/wix/react-native-notifications/issues/585#issuecomment-619096043

**Comment by bossajie** [comment]
Can I achieve it even I use npm insta this library on my react native project?

**Comment by danieloprado** [comment]
You can also use patch-package (https://www.npmjs.com/package/patch-package) since is a simple change.

**Comment by aniravi24** [comment]
This PR fixed background notifications on Android for me!
1. Foreground works already
2. Background works with this PR
3. App killed with getInitialNotification() works with what's currently in master.

**Comment by ttkien** [comment]
I accidentally choose close PR, then cannot reopen

**Comment by ttkien** [comment]
I re-open here https://github.com/wix/react-native-notifications/pull/614

**Pull request closed without merging**
