### PR TITLE
Docs for setNotificationChannel

### PR DESCRIPTION
**Pull request by alexbuicescu**
This PR is a follow up with documentation of the [previous PR](https://github.com/wix/react-native-notifications/pull/535) which added support for android's channels.

### CODE REVIEW

**Comment by alexbuicescu** [comment]
Are there other files where I need to add docs?

**Comment by JaioSkura** [comment]
Hi, 

Thanks a lot for this job. Really needed task.

Maybe I am missing something, but even if the channels are created, then in the getNotificationBuilder function, they are not used, are they? I think that notifications are still posted with the default channel. Am I wrong?

**Comment by alexbuicescu** [comment]
hi @JaioSkura I'm not entirely sure what you mean. If you are talking about a local notification, you might be correct. I didn't change/add anything for the local notifications.

In my tests whenever I sent a remote notification it was received on the correct channel (I tested with a custom sound and vibration pattern for that particular channel).

**Comment by JaioSkura** [comment]
Ups! ok! you are right, I am focused in local notifications, that is why I was confused. 
I will try to change it for local notifications, and add it in new PR. 

Thank a lot.

**Comment by JaioSkura** [comment]
Thanks a lot for accepting this change. I think that in npmjs there is not yet this version. In fact there is not the previous one neither. If you install the library with 'npn install react-native-notifications' or 'yarn add react-native-notifications' you still get the version without channels. As long as I understand this should be published there, shouldn't be? Is ther some reason for this delay?

Thanks again.

**Comment by alexbuicescu** [comment]
@JaioSkura you can checkout all releases [here](https://github.com/wix/react-native-notifications/releases). I use version **3.1.4-snapshot.114** and it works as expected

**Comment by JaioSkura** [comment]
Yeah, I now. And I already test it , but building it in local. What I mean is that it is not publiseh in npm. https://www.npmjs.com/package/react-native-notifications
If you check there the last version is previous to you PR, @alexbuicescu . It is still the version 3.1.4

**Pull request merged**
