### PR TITLE
Foreground notification fix on android

### PR DESCRIPTION
**Pull request by bossajie**
Blank notification on foreground only, you can receive notification but it is not working in foreground, only on background.

Thanks to this: https://github.com/wix/react-native-notifications/issues/525#issuecomment-656585578

### CODE REVIEW

**Comment by andreialecu** [comment]
I believe this was already fixed by a recent PR and merged but not released yet.

Try npm/yarn install `react-native-notifications@snapshot`. See https://www.npmjs.com/package/react-native-notifications?activeTab=versions

**Comment by bossajie** [comment]
> I believe this was already fixed by a recent PR and merged but not released yet.
> 
> Try npm/yarn install `react-native-notifications@snapshot`. See https://www.npmjs.com/package/react-native-notifications?activeTab=versions

image

I am getting this error when I am using the latest snapshot of the library.

**Comment by andreialecu** [comment]
Might be caused by https://github.com/wix/react-native-notifications/pull/634

I'm personally using `"react-native-notifications": "3.2.2-snapshot.145",` and it seems to work for foreground notifications as well.

**Comment by bossajie** [comment]
> Might be caused by #634
> 
> I'm personally using `"react-native-notifications": "3.2.2-snapshot.145",` and it seems to work for foreground notifications as well.

still not working for me

**Comment by jamesa3** [comment]
Can we approve this? Or at least have an option to enable foreground notifications on Android?

**Comment by yogevbd** [comment]
I'm not sure it's the right approach to enable foreground notifications for everyone. Some applications, and the Wix app is among them, listens to `registerNotificationReceivedForeground` and handles the notification presentation in JS.

Created [this task](https://github.com/wix/react-native-notifications/issues/668) for the next release.

**Pull request closed without merging**
